### ISSUE TITLE
DevTools 没办法编辑

### ISSUE THREAD

**Issue by JackChenLucky** [E024/MiniBlinkPinvoke#1]
用你的DEMO运行后。调试工具里面console 里面不能输入。官方的demo可以呢。是哪里有问题吗

**Comment by E024** [comment]
没有将按键消息发送给MiniBlink导致，已经修复了。

**Comment by JackChenLucky** [comment]
中文汉字输入会是乱码,复制粘贴中文是好的。需要把SendMessageA 换成SendMessageW 就可以了。

**Comment by E024** [comment]
已更新，谢谢。
