### ISSUE TITLE
MiniBlinkPinvokeDemo项目不可用

### ISSUE THREAD

**Issue by moumingtao** [E024/MiniBlinkPinvoke#5]
![4_rjrjhrfaiw 6clt zs b](https://user-images.githubusercontent.com/40648342/48259371-b3375800-e452-11e8-92fb-bbd427ae5947.png)

**Comment by E024** [comment]
这是分两个项目的，需要单独下载 https://github.com/E024/MiniBlinkPinvokeDemo
到相同目录
